apiVersion: v1
kind: Service
metadata:
  name: chaos-k8s-ifs-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaos-k8s-ifs.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: chaos-k8s-ifs
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.targetport}}
  selector:
    component: chaos-k8s-ifs
     {{- include "chaos-k8s-ifs.selectorLabels" . | nindent 4 }}
