apiVersion: v1
kind: Service
metadata:
  name: ci-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ci-manager.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: ci-manager
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.port}}
  - name: grpc-ci-manager
    port: {{.Values.service.grpcport}}
    protocol: TCP
    targetPort: {{.Values.service.grpcport}}
  selector:
     {{- include "ci-manager.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ci-manager-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ci-manager.labels" . | nindent 4 }}
      {{- if .Values.global.commonLabels }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
      {{- end }}
      {{- if .Values.global.commonAnnotations }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  clusterIP: None
  ports:
    - name: ci-manager
      port: {{.Values.service.port}}
      protocol: TCP
      targetPort: {{.Values.service.port}}
    - name: grpc-ci-manager
      port: {{.Values.service.grpcport}}
      protocol: TCP
      targetPort: {{.Values.service.grpcport}}
  selector:
    {{- include "ci-manager.selectorLabels" . | nindent 4 }}