apiVersion: v2
appVersion: 0.6.1
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: srm-ui
type: application
version: 1.12.0
