apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.additionalConfig "context" $) | nindent 2}}
  GITNESS_DEBUG: {{ .Values.config.CODE_DEBUG | quote }}
  GITNESS_TRACE: {{ .Values.config.CODE_TRACE | quote }}
  GITNESS_PROFILER_TYPE: {{ .Values.config.CODE_PROFILER_TYPE | quote }}
  GITNESS_PROFILER_SERVICE_NAME: {{ .Values.config.CODE_PROFILER_SERVICE_NAME | quote }}
  GITNESS_PUBLIC_RESOURCE_CREATION_ENABLED: {{ .Values.config.CODE_PUBLIC_RESOURCE_CREATION_ENABLED | quote }}
  GITNESS_DATABASE_DRIVER: {{ .Values.config.CODE_DATABASE_DRIVER | quote }}
  GITNESS_EVENTS_MODE: {{ .Values.config.CODE_EVENTS_MODE | quote }}
  GITNESS_PUBSUB_PROVIDER: {{.Values.config.CODE_PUBSUB_PROVIDER | quote}}
  GITNESS_PUBSUB_APP_NAMESPACE: {{.Values.config.CODE_PUBSUB_APP_NAMESPACE | quote}}

  GITNESS_REDIS_ENDPOINT: {{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "code-api" "unsetProtocol" true) }}
  GITNESS_REDIS_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  GITNESS_REDIS_SENTINEL_ENDPOINT: {{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "code-api" "unsetProtocol" true) }}

  HARNESS_REDIS_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote}}
  HARNESS_REDIS_SENTINEL_ENDPOINT: '{{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "events" "unsetProtocol" true) }}'
  HARNESS_REDIS_ENDPOINT: '{{ include "harnesscommon.dbv3.redisConnection" (dict "ctx" $ "database" "events" "unsetProtocol" true) }}'
  HARNESS_REDIS_CERT_PATH: {{ .Values.config.EVENTS_FRAMEWORK_REDIS_SSL_CA_PATH | quote }}
  HARNESS_REDIS_NAMESPACE: {{ .Values.config.EVENTS_FRAMEWORK_REDIS_NAMESPACE | quote }}

  GITNESS_URL_GIT:  {{ .Values.config.CODE_URL_GIT | default (printf "%s/code/git" .Values.global.loadbalancerURL) | quote }}
  GITNESS_URL_BASE: '{{ .Values.global.loadbalancerURL }}'
  GITNESS_URL_API: '{{ .Values.global.loadbalancerURL }}/gateway/code/api'
  GITNESS_URL_UI: '{{ .Values.global.loadbalancerURL }}'
  GITNESS_URL_INTERNAL: http://code-api.{{ .Release.Namespace }}.svc.cluster.local:80

  GITNESS_BLOBSTORE_BUCKET: {{ .Values.config.CODE_BLOBSTORE_BUCKET | quote }}
  GITNESS_BLOBSTORE_IMPERSONATION_LIFETIME: {{ .Values.config.CODE_BLOBSTORE_IMPERSONATION_LIFETIME | quote }}
  GITNESS_BLOBSTORE_PROVIDER: {{ .Values.config.CODE_BLOBSTORE_PROVIDER | quote }}
  GITNESS_BLOBSTORE_TARGET_PRINCIPAL: {{ .Values.config.CODE_BLOBSTORE_TARGET_PRINCIPAL| quote }}
  GITNESS_INSTRUMENTATION_ENABLE: {{.Values.config.CODE_INSTRUMENTATION_ENABLE | quote}}

  GITRPC_CLIENT_ADDR: {{ .Values.additionalConfig.GITRPC_CLIENT_ADDR | default (printf "kubernetes:///code-githa.%s.svc.cluster.local:3001" .Release.Namespace) | quote }}

  GITNESS_GRACEFUL_SHUTDOWN_TIME: {{ int .Values.config.CODE_SERVER_GRACEFUL_SHUTDOWN_TIME | printf "%ds" | quote }}

  ENABLE_CDN: {{ .Values.config.CODE_ENABLE_CDN | quote }}

  # Harness embedded values
  HARNESS_SERVICES_ACL_IGNORE: {{ .Values.config.CODE_HARNESS_SERVICES_ACL_IGNORE | quote }}

  HARNESS_SERVICES_ACL_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_ACL_CLIENT_BASEURL | default (printf "http://access-control.%s.svc.cluster.local:9006/api/" .Release.Namespace) | quote }}
  HARNESS_SERVICES_MANAGER_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_MANAGER_CLIENT_BASEURL | default (printf "http://harness-manager.%s.svc.cluster.local:9090/api/" .Release.Namespace) | quote }}
  HARNESS_SERVICES_NGMANAGER_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_NGMANAGER_CLIENT_BASEURL | default (printf "http://ng-manager.%s.svc.cluster.local:7090/" .Release.Namespace) | quote }}
  HARNESS_SERVICES_SEMANTIC_SEARCH_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_SEMANTIC_SEARCH_CLIENT_BASEURL | default (printf "http://semantic-search.%s.svc.cluster.local:9101" .Release.Namespace) | quote }}
  HARNESS_SERVICES_CODESEARCH_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_CODESEARCH_CLIENT_BASEURL | default (printf "http://code-search.%s.svc.cluster.local/api/" .Release.Namespace) | quote }}
  HARNESS_SERVICES_NOTIFICATION_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_NOTIFICATION_CLIENT_BASEURL | default (printf "http://platform-service.%s.svc.cluster.local:9005/api/" .Release.Namespace) | quote }}
  HARNESS_SERVICES_OPA_IGNORE: {{ .Values.config.CODE_HARNESS_SERVICES_OPA_IGNORE | quote }}
  HARNESS_SERVICES_OPA_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_OPA_CLIENT_BASEURL | default (printf "http://policy-mgmt.%s.svc.cluster.local:3000" .Release.Namespace) | quote }}
  HARNESS_SERVICES_AUDIT_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_AUDIT_CLIENT_BASEURL | default (printf "http://platform-service.%s.svc.cluster.local:9005/api" .Release.Namespace) | quote }}
  HARNESS_SERVICES_CIMANAGER_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_CIMANAGER_CLIENT_BASEURL | default (printf "http://ci-manager.%s.svc.cluster.local:4457/" .Release.Namespace) | quote }}
  HARNESS_SERVICES_SSCA_CLIENT_BASEURL: {{ .Values.additionalConfig.HARNESS_SERVICES_SSCA_CLIENT_BASEURL | default (printf "http://ssca-manager.%s.svc.cluster.local:7090/" .Release.Namespace) | quote }}
  HARNESS_WEBHOOK_INTERNAL_URL: {{ .Values.additionalConfig.HARNESS_WEBHOOK_INTERNAL_URL | default (printf "http://ng-manager.%s.svc.cluster.local:7090/" .Release.Namespace) | quote }}
  # Artifact Registry values
  GITNESS_URL_REGISTRY: {{ .Values.config.REGISTRY_URL | quote }}

  # serve uiv2 only if codev2 is enabled
  {{- if .Values.experimental.codev2Enabled }}
  HARNESS_DEVELOPMENT_UIV2_SOURCE: "/app/uiv2"
  {{ end }}
