apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "code-api.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
    protocol: TCP
    name: http
  - port: {{ .Values.service.sshPort }}
    targetPort: 3022
    protocol: TCP
    name: ssh
  selector:
    app: {{ include "code-api.name" . }}