{{- if .Values.dockercfg }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "code-gitrpc.name" . }}-dockercfg
  namespace: {{ .Release.Namespace }}
  annotations:
    harness.io/skip-versioning: "true"
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.dockercfg | quote }}
{{- end}}