apiVersion: v2
appVersion: v0.81.3
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: Harness GitOps
name: gitops
type: application
version: 1.30.2
