apiVersion: v1
kind: Service
metadata:
  name: ff-pushpin-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ff-pushpin-service.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: "port17001"
    port: {{.Values.service.port17001}}
    protocol: TCP
    targetPort: {{.Values.service.targetport17001}}
  - name: "port17002"
    port: {{.Values.service.port17002}}
    protocol: TCP
    targetPort: {{.Values.service.targetport17002}}
  - name: "port17003"
    port: {{.Values.service.port17003}}
    protocol: TCP
    targetPort: {{.Values.service.targetport17003}}
  selector:
     {{- include "ff-pushpin-service.selectorLabels" . | nindent 4 }}
