apiVersion: v2
appVersion: 0.0.81904
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: ce-nextgen
type: application
version: 1.47.2
