apiVersion: v1
kind: Service
metadata:
  name: chaos-linux-ifc-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "chaos-linux-ifc.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: chaos-linux-ifc
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetport}}
  selector:
    component: chaos-linux-ifc
   {{- include "chaos-linux-ifc.selectorLabels" . | nindent 4 }}
