apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ng-auth-ui.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ng-auth-ui.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- include "harnesscommon.generateSecretsInHelpers" (dict "ctx" $) | indent 2 }}
