apiVersion: v2
appVersion: 0.10.0
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: service-discovery-manager
type: application
version: 0.37.6
