apiVersion: v2
appVersion: 0.0.70042
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: anomaly-detection
type: application
version: 1.8.0
