apiVersion: v1
kind: Service
metadata:
  name: le-nextgen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "le-nextgen.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: learning
      port: {{.Values.service.port}}
      protocol: TCP
      targetPort: {{.Values.service.port}}
  selector:
    {{- include "le-nextgen.selectorLabels" . | nindent 4 }}
  type: {{.Values.service.type}}
