{{- include "harnesscommon.pdb.renderPodDistributionBudget" (dict "ctx" $) }}
---
{{- if or $.Values.global.pdb.create $.Values.pdb.create }}
{{- $labelsFunction := printf "harness-manager-iterator.labels" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harness-manager-iterator
  namespace: {{ $.Release.Namespace }}
  labels: {{ include $labelsFunction $ | nindent 4 }}
  {{- if $.Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" $.Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" $.Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- $minAvailable := "" }}
  {{- $maxUnavailable := "" }}
  {{- if $.Values.global.pdb.minAvailable }}
      {{- $minAvailable = $.Values.global.pdb.minAvailable }}
  {{- end }}
  {{- if $.Values.pdb.minAvailable }}
      {{- $minAvailable = $.Values.pdb.minAvailable }}
  {{- end }}
  {{- if $.Values.global.pdb.maxUnavailable }}
      {{- $maxUnavailable = $.Values.global.pdb.maxUnavailable }}
  {{- end }}
  {{- if $.Values.pdb.maxUnavailable }}
      {{- $maxUnavailable = $.Values.pdb.maxUnavailable }}
  {{- end }}
  {{- if $minAvailable }}
  minAvailable: {{ $minAvailable }}
  {{- else }}
  {{- if $maxUnavailable }}
  maxUnavailable: {{ $maxUnavailable }}
  {{- else }}
  minAvailable: "50%"
  {{- end }}
  {{- end }}
  {{- $selectorFunction := printf "harness-manager-iterator.selectorLabels" }}
  selector:
    matchLabels: {{ include $selectorFunction $ | nindent 6 }}
{{- end }}