{{ include "harnesscommon.monitoring.podMonitor" (dict "name" "harness-manager" "ctx" $ "label" "app.kubernetes.io/name") }}
---
{{ include "harnesscommon.monitoring.podMonitor" (dict "name" "harness-manager-iterator" "podMonitorName" "harness-manager-iterator" "ctx" $ "label" "app.kubernetes.io/name") }}