apiVersion: v1
kind: Service
metadata:
  name: {{ include "change-data-capture.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "change-data-capture.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.annotations }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
    - name: http
      port: {{.Values.service.port}}
      protocol: TCP
      targetPort: 8190
  selector:
    {{- include "change-data-capture.selectorLabels" . | nindent 4 }}

---

{{- if .Values.splitDeployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "change-data-capture-pms.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "change-data-capture.labels" . | nindent 4 }}
      {{- if .Values.global.commonLabels }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
  annotations:
    {{- if .Values.service.annotations }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
      {{- end }}
      {{- if .Values.global.commonAnnotations }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
    - name: http
      port: {{.Values.service.port}}
      protocol: TCP
      targetPort: 8190
  selector:
    app: {{ include "change-data-capture-pms.name" . }}
    {{- include "change-data-capture.selectorLabels" . | nindent 4 }}
{{- end }}
