apiVersion: v1
kind: ConfigMap
metadata:
  name: ng-manager
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.config "context" $) | nindent 2}}
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
  {{- include "harnesscommon.monitoring.config" . | nindent 2 }}
  {{- include "harnesscommon.logging.setFileLogging" . | nindent 2 }}

{{- if .Values.oidc.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-config-ng-manager
  namespace: '{{ .Release.Namespace }}'
  {{- if .Values.global.commonLabels }}
  labels:
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  oidc_config.json: |
    {
      "OPENID_CONFIGURATION" : {
        "issuer": "{{ .Values.global.loadbalancerURL }}/ng/api/oidc/account/{account_id}",
        "jwks_uri": "{{ .Values.global.loadbalancerURL }}/ng/api/oidc/account/{account_id}/.wellknown/jwks",
        "subject_types_supported":["public","pairwise"],
        "response_types_supported":["id_token"],
        "claims_supported":
        [
          "sub","aud","exp","iat","iss","account_id"
        ],
        "id_token_signing_alg_values_supported":["RS256"],
        "scopes_supported":["openid"]
      },
      "AWS": {
        "header": {
          "typ": "JWT",
          "alg": "RS256",
          "kid": "GENERATE_AT_RUNTIME"
        },
        "payload": {
          "sub": "{account_id}",
          "aud": "sts.amazonaws.com",
          "iss": "{{ .Values.global.loadbalancerURL }}/ng/api/oidc/account/{account_id}",
          "exp": 3600,
          "iat": 0,
          "account_id": "{account_id}"
        }
      },
      "CUSTOM": {
        "header": {
          "typ": "JWT",
          "alg": "RS256",
          "kid": "GENERATE_AT_RUNTIME"
        },
        "payload": {
          "sub": "{account_id}",
          "iss": "{{ .Values.global.loadbalancerURL }}/ng/api/oidc/account/{account_id}",
          "exp": 3600,
          "iat": 0,
          "account_id": "{account_id}"
        }
      },
      "GCP": {
        "header": {
          "typ": "JWT",
          "alg": "RS256",
          "kid": "GENERATE_AT_RUNTIME"
        },
        "payload": {
          "sub": "{account_id}",
          "aud": "https://iam.googleapis.com/projects/{gcp_project_id}/locations/global/workloadIdentityPools/{workload_pool_id}/providers/{provider_id}",
          "iss": "{{ .Values.global.loadbalancerURL }}/ng/api/oidc/account/{account_id}",
          "exp": 3600,
          "iat": 0,
          "account_id": "{account_id}"
        },
        "access_token_sts_endpoint": "https://sts.googleapis.com",
        "access_token_iam_sa_credentials_endpoint": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/",
        "workload_access_token_config": {
          "audience": "//iam.googleapis.com/projects/{gcp_project_id}/locations/global/workloadIdentityPools/{workload_pool_id}/providers/{provider_id}",
          "grant_type": "urn:ietf:params:oauth:grant-type:token-exchange",
          "requested_token_type": "urn:ietf:params:oauth:token-type:access_token",
          "scope": "https://www.googleapis.com/auth/cloud-platform",
          "subject_token_type": "urn:ietf:params:oauth:token-type:id_token",
          "subject_token": "{SUBJECT_TOKEN_TYPE}",
          "options": {
            "userProject": "{gcp_project_id}"
          }
        }
      },
      "VAULT": {
        "header": {
          "typ": "JWT",
          "alg": "RS256",
          "kid": "GENERATE_AT_RUNTIME"
        },
        "payload": {
          "sub": "{account_id}",
          "aud": "{vault_jwt_auth_path}",
          "iss": "{{ .Values.global.loadbalancerURL }}/ng/api/oidc/account/{account_id}",
          "exp": 3600,
          "iat": 0,
          "account_id": "{account_id}"
        }
      }
    }
{{- end }}

{{- if .Values.licenseManager.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-essentials-config-ng-manager
  namespace: '{{ .Release.Namespace }}'
  {{- if .Values.global.commonLabels }}
  labels:
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  license_manager_config.json: |
    {
      "PRODUCT_CONFIGURATIONS" : [
        {
          "LICENSING_MODEL" : {
            "LICENSING_TYPE" : "DEVOPS_ESSENTIALS"
          },
          "PRICING_MODEL" : [
            {
              "MODULE_TYPE": "HARNESS_CD",
              "PREPAY_UNIT_COST": 0.5,
              "POSTPAY_UNIT_COST": 0.575,
              "INCLUDED_QUANTITY": 25000,
              "PREPAY_EXTENSION_QUANTITY": 5000
            },
            {
              "MODULE_TYPE": "HARNESS_CI",
              "PREPAY_UNIT_COST": 0.005,
              "POSTPAY_UNIT_COST": 0.00575,
              "INCLUDED_QUANTITY": 300000,
              "PREPAY_EXTENSION_QUANTITY": 2500000
            },
            {
              "MODULE_TYPE": "HARNESS_STO",
              "PREPAY_UNIT_COST": 1,
              "POSTPAY_UNIT_COST": 1.15,
              "INCLUDED_QUANTITY": 3600,
              "PREPAY_EXTENSION_QUANTITY": 2500
            },
            {
              "MODULE_TYPE": "HARNESS_IACM",
              "PREPAY_UNIT_COST": 1.5,
              "POSTPAY_UNIT_COST": 1.725,
              "INCLUDED_QUANTITY": 500,
              "PREPAY_EXTENSION_QUANTITY": 1700
            }
          ]
        }
      ]
    }
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cgi-config-ng-manager
  namespace: '{{ .Release.Namespace }}'
  {{- if .Values.global.commonLabels }}
  labels:
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  cgi-config.yaml: |
    {{- include "ng-manager.generate.cgiConfig" .Values.cgiConfig | nindent 2 }}