apiVersion: v2
appVersion: 0.0.release-223
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: ti-service
type: application
version: 1.44.0
