apiVersion: v2
appVersion: 0.0.release-181-ubi
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: scm-service
type: application
version: 1.20.1
