apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: debezium-service
type: application
version: 1.21.0
