apiVersion: v1
kind: ConfigMap
metadata:
  name: harness-manager-config
  namespace: '{{ .Release.Namespace }}'
  {{- if .Values.global.commonLabels }}
  labels:
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: 
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.config "context" $) | nindent 2}}
  {{- if .Values.global.mongoSSL }}
  MONGO_SSL_CONFIG: "true"
  MONGO_SSL_CA_TRUST_STORE_PATH: /opt/harness/keystore.jks
  MONGO_SSL_CA_TRUST_STORE_PASSWORD: password
  {{- end }}
  {{- if .Values.global.proxy.enabled }}
  PROXY_ENABLED: '{{ .Values.global.proxy.enabled }}'
  PROXY_HOST: '{{ .Values.global.proxy.host }}'
  PROXY_PORT: '{{ .Values.global.proxy.port }}'
  PROXY_USERNAME: '{{ .Values.global.proxy.username }}'
  PROXY_PASSWORD: '{{ .Values.global.proxy.password }}'
  PROXY_PROTOCOL: '{{ .Values.global.proxy.protocol }}'
  {{- end }}
  {{- if .Values.global.awsServiceEndpointUrls.enabled }}
  AWS_SERVICE_ENDPOINT_URLS_ENABLED: '{{ .Values.global.awsServiceEndpointUrls.enabled }}'
  AWS_SERVICE_ENDPOINT_URLS_ENDPOINT_REGION: {{ .Values.global.awsServiceEndpointUrls.endPointRegion }}
  AWS_SERVICE_ENDPOINT_URLS_STS_ENDPOINT_URL: {{ .Values.global.awsServiceEndpointUrls.stsEndPointUrl }}
  AWS_SERVICE_ENDPOINT_URLS_ECS_ENDPOINT_URL: {{ .Values.global.awsServiceEndpointUrls.ecsEndPointUrl }}
  AWS_SERVICE_ENDPOINT_URLS_CLOUDWATCH_ENDPOINT_URL: {{ .Values.global.awsServiceEndpointUrls.cloudwatchEndPointUrl }}
  {{- end }}
  {{- if .Values.global.ng.enabled }}
  NG_MANAGER_BASE_URL: 'http://ng-manager:7090/'
  ACCESS_CONTROL_ENABLED: "true"
  ACCESS_CONTROL_BASE_URL: 'http://access-control:9006/api/'
  ENABLE_AUDIT: 'true'
  AUDIT_CLIENT_BASEURL: 'http://platform-service:9005/api/'
  PIPELINE_CLIENT_BASEURL: 'http://pipeline-service:12001/api/'
  NOTIFICATION_BASE_URL: 'http://platform-service:9005/api/'
  {{- end }}
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
  {{- include "harnesscommon.monitoring.config" . | nindent 2 }}
  {{- include "harnesscommon.logging.setFileLogging" . | nindent 2 }}

