# Default values for chaos-crd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  crd:
    enabled: true
image:
  registry: docker.io
  repository:
  tag: "null"
