apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "template-service.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  name: template-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc-template
    port: {{ .Values.service.grpcport }}
    protocol: TCP
    targetPort: {{ .Values.service.grpcport }}
  - name: http-template
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  - name: grpc-gitsync
    port: {{ .Values.service.gitsyncgrpcport }}
    protocol: TCP
    targetPort: {{ .Values.service.gitsyncgrpcport }}
  selector:
    {{- include "template-service.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{.Values.service.type}}
