{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "service-discovery-manager.name" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "service-discovery-manager.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "service-discovery-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}