apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "pipeline-service.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  name: pipeline-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc-pms
    port: {{ .Values.service.grpcport }}
    protocol: TCP
    targetPort: {{ .Values.service.grpcport }}
  - name: http-pms
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  - name: grpc-gitsync
    port: {{ .Values.service.gitsyncgrpcport }}
    protocol: TCP
    targetPort: {{ .Values.service.gitsyncgrpcport }}
  - name: grpc-pms-sdk
    port: {{ .Values.service.pmssdkgrpcport }}
    protocol: TCP
    targetPort: {{ .Values.service.pmssdkgrpcport }}
  selector:
    {{- include "pipeline-service.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{.Values.service.type}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "pipeline-service.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  name: pipeline-service-headless
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: grpc-pms
      port: {{ .Values.service.grpcport }}
      protocol: TCP
      targetPort: {{ .Values.service.grpcport }}
    - name: grpc-gitsync
      port: {{ .Values.service.gitsyncgrpcport }}
      protocol: TCP
      targetPort: {{ .Values.service.gitsyncgrpcport }}
    - name: sdk-grpc-pms
      port: {{ .Values.service.pmssdkgrpcport }}
      protocol: TCP
      targetPort: {{ .Values.service.pmssdkgrpcport }}
  selector:
    {{- include "pipeline-service.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  clusterIP: None
  type: {{.Values.service.type}}