apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: harness-common
  repository: https://harness.github.io/helm-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: queue-service
type: application
version: 1.7.1
